version: '3.8'

services:
  peptidia:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./results:/app/results
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped