name: CI

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.12']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Smoke test imports
        shell: bash
        run: |
          python - <<'PY'
          import streamlit, pandas, numpy, pyarrow, plotly, matplotlib, seaborn
          import sklearn, xgboost, scipy, shap, numba
          print('OK')
          PY
